//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OBIC\\受注ファイル\\")]
        public string EOSDORASTAJYUTYUDIR {
            get {
                return ((string)(this["EOSDORASTAJYUTYUDIR"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OBIC\\受注ファイル\\")]
        public string EOSDORASTAJYUTYUFILE {
            get {
                return ((string)(this["EOSDORASTAJYUTYUFILE"]));
            }
            set {
                this["EOSDORASTAJYUTYUFILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OBIC7S4\\EXCEL受注取込\\EXCEL受注取込元データ.xls")]
        public string EXCEL受注取込ファイル {
            get {
                return ((string)(this["EXCEL受注取込ファイル"]));
            }
            set {
                this["EXCEL受注取込ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OBIC\\受注ファイル\\受信20160112-14E.csv")]
        public string EOSドラスタ受注取込ファイル {
            get {
                return ((string)(this["EOSドラスタ受注取込ファイル"]));
            }
            set {
                this["EOSドラスタ受注取込ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OBIC7S4\\monotaRO\\受注取込\\")]
        public string monotaRO受注取込フォルダ {
            get {
                return ((string)(this["monotaRO受注取込フォルダ"]));
            }
            set {
                this["monotaRO受注取込フォルダ"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.106;Initial Catalog=SPEEDDB;User Id=goda;Password=goda")]
        public string SPEEDDBConnectionString {
            get {
                return ((string)(this["SPEEDDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=SPEEDDB;uid=goda;pwd=goda")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
    }
}
